# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_racetime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetime',
            name='date',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
    ]
