# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170713_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetime',
            name='meet',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='event',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='firstName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='lastName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='session',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='team',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='time',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
