# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_racetime_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetime',
            name='bib',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='event',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='firstName',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='gender',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='host',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='lastName',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='location',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='meet',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='score',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='session',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='team',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='racetime',
            name='time',
            field=models.CharField(default='N/A', max_length=25),
        ),
    ]
