# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170715_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetime',
            name='sessionOrder',
            field=models.IntegerField(default=0),
        ),
    ]
